// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/auth/domain/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/auth/domain/repository.go -destination=internal/modules/auth/domain/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "taskmanagement/internal/modules/auth/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ByEmail mocks base method.
func (m *MockRepository) ByEmail(arg0 context.Context, arg1 string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByEmail", arg0, arg1)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByEmail indicates an expected call of ByEmail.
func (mr *MockRepositoryMockRecorder) ByEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByEmail", reflect.TypeOf((*MockRepository)(nil).ByEmail), arg0, arg1)
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 context.Context, arg1 domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0, arg1)
}

// CreateRefresh mocks base method.
func (m *MockRepository) CreateRefresh(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefresh", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefresh indicates an expected call of CreateRefresh.
func (mr *MockRepositoryMockRecorder) CreateRefresh(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefresh", reflect.TypeOf((*MockRepository)(nil).CreateRefresh), arg0, arg1, arg2, arg3)
}

// DeleteRefresh mocks base method.
func (m *MockRepository) DeleteRefresh(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefresh", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefresh indicates an expected call of DeleteRefresh.
func (mr *MockRepositoryMockRecorder) DeleteRefresh(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefresh", reflect.TypeOf((*MockRepository)(nil).DeleteRefresh), arg0, arg1)
}

// RotateRefresh mocks base method.
func (m *MockRepository) RotateRefresh(arg0 context.Context, arg1, arg2, arg3, arg4 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateRefresh", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateRefresh indicates an expected call of RotateRefresh.
func (mr *MockRepositoryMockRecorder) RotateRefresh(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateRefresh", reflect.TypeOf((*MockRepository)(nil).RotateRefresh), arg0, arg1, arg2, arg3, arg4)
}
