package errorcode

const (
	InvalidRequest             = "invalid_request"
	InvalidIdempotencyKey      = "invalid_idempotency_key"
	Unauthorized               = "unauthorized"
	Forbidden                  = "forbidden"
	NotFound                   = "not_found"
	Conflict                   = "conflict"
	OwnerCannotBeRemoved       = "owner_cannot_be_removed"
	UserAlreadyTeamMember      = "user_already_team_member"
	MemberHasActiveAssignments = "member_has_active_assignments"
	InternalError              = "internal_error"
	InvalidJSON                = "invalid_json"
	PayloadTooLarge            = "payload_too_large"
	InvalidField               = "invalid_field"
	InvalidPagination          = "invalid_pagination"
	InvalidStatus              = "invalid_status"
	InvalidID                  = "invalid_id"
	InvalidTeamID              = "invalid_team_id"
	InvalidAssigneeID          = "invalid_assignee_id"
	InvalidEmail               = "invalid_email"
	InvalidPassword            = "invalid_password"
	TaskCreated                = "task_created"
	TaskUpdated                = "task_updated"
	TaskStatusChanged          = "task_status_changed"
	TaskDeleted                = "task_deleted"
	TaskAssigned               = "task_assigned"
	TaskUnassigned             = "task_unassigned"
	TaskStatusTodo             = "todo"
	TaskStatusInProgress       = "in_progress"
	TaskStatusDone             = "done"
)
